name: Get_Next_Line Tests
run-name: test Get_Next_Line
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test_get_next_line:
    runs-on: ubuntu-latest
    steps:
      # 環境構築
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y valgrind

      # リポジトリのコードを取得
      - name: Checkout code
        uses: actions/checkout@v5
      
      # 実行
      - name: Compile and Run test
        run: ./gnl.sh
        shell: bash
      