name: Get_Next_Line Tests
run-name: test Get_Next_Line
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test_get_next_line:
    runs-on: ubuntu-latest
    steps:
      # リポジトリのコードを取得
      - name: Checkout code
        uses: actions/checkout@v5
      
      # 実行
      - name: compile and run test
        run: ../../gnl.sh
        shell: bash
      